export const THEMES = [
  {
    id: "winter-fireside",
    name: "Winter Fireside",
    scent: "Clove & Smoked Vanilla",
    clothing: "Cream knits",
    background: "assets/themes/winter-fireside.jpg",
    sample: "assets/samples/winter-fireside.jpg",
    props: ["beanie", "scarf"],
    candle: { x: 0.84, y: 0.74, scale: 0.3 },
    subject: { scale: 0.88, y: 0.06 },
    grade: { tint: [255, 132, 52], warm: 0.3, dark: 0.14 },
    particles: "snow",
  },
  {
    id: "mykonos",
    name: "Mykonos Sunset",
    scent: "Mykonos Sunset",
    clothing: "Linen & sun",
    background: "assets/themes/mykonos.jpg",
    sample: "assets/samples/mykonos.jpg",
    props: ["sunhat", "sunglasses"],
    candle: { x: 0.86, y: 0.76, scale: 0.26 },
    subject: { scale: 0.86, y: 0.1 },
    grade: { tint: [255, 168, 88], warm: 0.34, dark: 0.08 },
    particles: "sparkle",
  },
  {
    id: "autumn",
    name: "Autumn Orchard",
    scent: "Toasted Vanilla Pumpkin",
    clothing: "Harvest flannel",
    background: "assets/themes/autumn-orchard.jpg",
    sample: "assets/samples/autumn.jpg",
    props: ["autumn-scarf"],
    candle: { x: 0.85, y: 0.75, scale: 0.28 },
    subject: { scale: 0.9, y: 0.06 },
    grade: { tint: [232, 120, 40], warm: 0.32, dark: 0.1 },
    particles: "leaves",
  },
  {
    id: "winter-woods",
    name: "Winter Woods",
    scent: "Winter Woods",
    clothing: "Wool & pine",
    background: "assets/themes/winter-woods.jpg",
    sample: "assets/samples/winter-woods.jpg",
    props: ["beanie", "scarf"],
    candle: { x: 0.83, y: 0.73, scale: 0.29 },
    subject: { scale: 0.9, y: 0.05 },
    grade: { tint: [180, 210, 230], warm: 0.1, dark: 0.16 },
    particles: "snow",
  },
  {
    id: "champagne",
    name: "Champagne Night",
    scent: "Oud & Rose",
    clothing: "After dark",
    background: "assets/themes/champagne-night.jpg",
    sample: "assets/samples/champagne.jpg",
    props: ["sunglasses"],
    candle: { x: 0.86, y: 0.74, scale: 0.27 },
    subject: { scale: 0.86, y: 0.08 },
    grade: { tint: [212, 176, 80], warm: 0.18, dark: 0.2 },
    particles: "sparkle",
  },
  {
    id: "holiday",
    name: "Holiday Hearth",
    scent: "Holiday Mulled Cider",
    clothing: "Festive knits",
    background: "assets/themes/holiday-hearth.jpg",
    sample: "assets/samples/holiday.jpg",
    props: ["beanie", "scarf"],
    candle: { x: 0.84, y: 0.74, scale: 0.29 },
    subject: { scale: 0.88, y: 0.06 },
    grade: { tint: [255, 110, 48], warm: 0.28, dark: 0.12 },
    particles: "sparkle",
  },
];

export function themeById(id) {
  return THEMES.find((theme) => theme.id === id) ?? THEMES[0];
}
